# RocketMQ
rocketmq:
  # docker容器内部访问宿主机http://host.docker.internal 127.0.0.1
  name-server: host.docker.internal:9876
  producer:
    group: i-home-producer
  consumer:
    group: i-home-consumer
  i-home-conf:
    normal-topic: normal-message-test
